/mnt/c/CAO/lab8/Core/alu_logic.sv
/mnt/c/CAO/lab8/Core/branch_comp.sv
/mnt/c/CAO/lab8/Core/Branch_Control.sv
/mnt/c/CAO/lab8/Core/control_unit.sv
/mnt/c/CAO/lab8/Core/Flush_regs.sv
/mnt/c/CAO/lab8/Core/fwd_logic.sv
/mnt/c/CAO/lab8/Core/hazard_detection.sv
/mnt/c/CAO/lab8/Core/imm_gen.sv
/mnt/c/CAO/lab8/Core/pipe_reg.sv
/mnt/c/CAO/lab8/Core/pc_pipe_reg.sv
/mnt/c/CAO/lab8/Core/program_counter.sv
/mnt/c/CAO/lab8/Core/reg_file.sv
/mnt/c/CAO/lab8/tb/pkg.sv
/mnt/c/CAO/lab8/tb/tracer_pkg.sv
/mnt/c/CAO/lab8/tb/tracer.sv
/mnt/c/CAO/lab8/Core/rv32i_top.sv
/mnt/c/CAO/lab8/Core/imem.sv
/mnt/c/CAO/lab8/Core/dmem.sv
/mnt/c/CAO/lab8/tb/tb_top.sv

